### ISSUE TITLE
`meyer_reset` does not fully replace `compass/reset`

### ISSUE THREAD

**Issue by petitJAM** [tenforwardconsulting/jefferies_tube#55]
#50 removed Compass from JT.  The `compass/reset` CSS that was being auto-included was replaced with `meyer_reset`.  However, it's not a perfect replacement.

In my specific instance, `compass/reset` was adding `vertical-align: middle` to `td` elements:

```css
caption,
th,
td {
 text-align:left;
 font-weight:normal;
 vertical-align:middle;
}
```

This is easy to fix as a one-off, but I don't know what else `meyer_reset` is missing that the various projects using this will miss.
